# Site settings
title: "My transgirl issues"
email: webmaster@joaz.de
description: "This is Jennifer Glauches personal blog about being a trans girl, depression, discrimination and transition issues"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  Joaz

# Build settings
markdown: kramdown


